import { NextResponse } from "next/server";
import { createClient } from "@sanity/client";

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ?? "67x2nc7r",
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production",
  token: process.env.SANITY_WRITE_TOKEN,
  apiVersion: "2024-01-01",
  useCdn: false,
});

function b(key: string, style: string, text: string) {
  return { _type: "block", _key: key, style, markDefs: [], children: [{ _type: "span", _key: key + "s", text, marks: [] }] };
}

export async function GET() {
  try {

    // ─── homePage ─────────────────────────────────────────────────────────────
    await client.createOrReplace({
      _id: "homePage",
      _type: "homePage",
      heroTitle: "Der digitale Assistent für Bausachverständige.",
      heroSubtext: "Vom Beweisbeschluss bis zum fertigen Gutachten — strukturiert, nachvollziehbar und rechtssicher. Entwickelt für die tägliche Arbeit vor Gericht und vor Ort.",
      heroPrimaryButton: "Alle Funktionen entdecken",
      heroSecondaryButton: "So funktioniert es",
      trustItems: [
        { _key: "t1", icon: "shield", label: "DSGVO-konform" },
        { _key: "t2", icon: "dns", label: "Deutsche Server" },
        { _key: "t3", icon: "lock", label: "256-bit Verschlüsselung" },
        { _key: "t4", icon: "policy", label: "EU AI Act ready" },
        { _key: "t5", icon: "person_check", label: "Menschliche Kontrolle" },
        { _key: "t6", icon: "verified", label: "Made in Germany" },
      ],
      stats: [
        { _key: "s1", value: "18", label: "Beweisfragen strukturiert", highlight: true },
        { _key: "s2", value: "3", label: "Exportformate (PDF, Word, Druck)", highlight: false },
        { _key: "s3", value: "100%", label: "Datenhoheit beim Sachverständigen", highlight: false },
        { _key: "s4", value: "< 1 Tag", label: "Einarbeitungszeit", highlight: false },
      ],
      problemTitle: "Warum der bisherige Weg nicht mehr ausreicht.",
      problemSubtext: "Gutachten entstehen heute noch überwiegend manuell — trotz hoher Fallzahlen, steigendem Termindruck und wachsender Dokumentationsanforderungen.",
      problemItems: [
        "Beweisbeschlüsse manuell übertragen und strukturieren.",
        "Fotos vom Ortstermin unsortiert und ohne Fallbezug.",
        "Gutachten-Entwurf in Word — Layout-Frust inklusive.",
      ],
      solutionItems: [
        "Beweisbeschluss hochladen — Struktur entsteht automatisch.",
        "Unterlagen, Fotos und Notizen fallbezogen in der digitalen Akte.",
        "Gutachten exportieren als PDF oder Word — strukturiert und fertig.",
      ],
      featuresTitle: "Alle Werkzeuge auf einen Blick.",
      featuresSubtext: "Von der Fallanlage bis zum Export.",
      features: [
        { _key: "f1", icon: "folder_open", title: "Fallverwaltung", description: "Akte, Beweisbeschluss, Ortstermin und Gutachten als strukturierte Einheit." },
        { _key: "f2", icon: "inventory_2", title: "Digitale Akte", description: "Unterlagen, Fotos und PDFs fallbezogen abgelegt und filterbar." },
        { _key: "f3", icon: "quiz", title: "Beweisfragen-Editor", description: "18 Beweisfragen mit Behauptung, Hinweis und Feststellungen." },
        { _key: "f4", icon: "mic", title: "Ortstermin-Modus", description: "Fotos, Diktate und Notizen direkt vor Ort erfassen." },
        { _key: "f5", icon: "auto_awesome", title: "KI-Assistent", description: "Textvorschläge und Norm-Matching auf Basis des Beweisbeschlusses." },
        { _key: "f6", icon: "sim_card_download", title: "Export PDF & Word", description: "Fertiges Gutachten strukturiert exportieren — bereit zur Einreichung." },
      ],
      ablaufTitle: "In drei Schritten zum fertigen Gutachten.",
      ablaufSubtext: "Kein langer Einarbeitungsaufwand. Der Workflow folgt dem, was Sachverständige ohnehin tun — nur strukturierter.",
      ablaufSteps: [
        { _key: "a1", step: "01", icon: "create_new_folder", title: "Fall anlegen", description: "Verfahrensdaten, Parteien und Beweisbeschluss erfassen. Der Fall ist sofort einsatzbereit." },
        { _key: "a2", step: "02", icon: "upload_file", title: "Unterlagen & Fotos einpflegen", description: "Dokumente in die digitale Akte laden, Fotos vom Ortstermin zuordnen. Alles fallbezogen." },
        { _key: "a3", step: "03", icon: "picture_as_pdf", title: "Gutachten generieren & exportieren", description: "Beweisfragen beantworten, KI-Assistenz nutzen. Export als PDF oder Word." },
      ],
      ablaufButtonText: "Den vollständigen Ablauf ansehen →",
      fuerWenTitle: "Für wen ist der Gutachten Assistent?",
      fuerWenSubtext: "Entwickelt für Sachverständige, die gerichtliche Gutachten unter Zeitdruck und mit hohem Qualitätsanspruch erstellen.",
      fuerWenItems: [
        { _key: "w1", icon: "gavel", title: "Öffentlich bestellte und vereidigte Sachverständige", description: "Gerichtsgutachten nach Beweisbeschluss — strukturiert, nachvollziehbar und mit vollständiger Dokumentation." },
        { _key: "w2", icon: "engineering", title: "Freie Bausachverständige", description: "Privatgutachten, Mängelrügen und Zustandsbeschreibungen effizienter erstellen." },
        { _key: "w3", icon: "account_balance", title: "Gutachterbüros mit mehreren Sachverständigen", description: "Einheitliche Falldokumentation und nachvollziehbare Gutachtenhistorie für das gesamte Team." },
      ],
      blogTitle: "Aus dem Blog.",
      blogSubtext: "Fachbeiträge rund um KI, Gutachtenwesen und digitale Prozesse.",
      blogLinkText: "Alle Beiträge →",
      offerBadge: "Früher Zugang",
      offerTitle: "Jetzt mit dem Gutachten Assistenten starten.",
      offerSubtext: "Testen Sie den vollen Funktionsumfang unverbindlich.",
      offerItems: [
        "Vollständige Fallverwaltung inklusive",
        "Digitale Akte mit Filterung",
        "Gutachten-Export als PDF und Word",
      ],
      offerButtonText: "Zugang anfragen",
      ctaTitle: "Bereit für strukturierte Gutachtenarbeit?",
      ctaSubtext: "Weniger manuelle Arbeit, mehr Nachvollziehbarkeit.",
      ctaPrimaryButtonText: "Zugang anfragen",
      ctaPrimaryButtonLink: "/kontakt",
      ctaSecondaryButtonText: "Alle Funktionen ansehen",
      ctaSecondaryButtonLink: "/funktionen",
    });

    // ─── datenschutz ──────────────────────────────────────────────────────────
    await client.createOrReplace({
      _id: "datenschutz",
      _type: "datenschutz",
      sections: [
        { _key: "ds1", title: "1. Verantwortlicher", content: "Verantwortlicher im Sinne der DSGVO ist:\n\nintersignum UG (haftungsbeschränkt)\nPasewalker Str. 15\n13127 Berlin\nE-Mail: info@intersignum.de" },
        { _key: "ds2", title: "2. Hosting", content: "Diese Website wird gehostet bei Vercel Inc., 340 Pine Street, Suite 701, San Francisco, CA 94104, USA. Vercel ist zertifiziert nach dem EU-US Data Privacy Framework. Bei jedem Aufruf unserer Website werden automatisch Verbindungsdaten (IP-Adresse, Datum, Uhrzeit, aufgerufene Seite) verarbeitet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse am sicheren Betrieb der Website)." },
        { _key: "ds3", title: "3. Kontaktformular", content: "Wenn Sie uns über das Kontaktformular eine Nachricht übermitteln, werden Ihre Angaben (Name, E-Mail-Adresse, Telefonnummer, Unternehmen, Nachricht) zur Bearbeitung Ihrer Anfrage verarbeitet. Die Daten werden über den Dienst Brevo (Sendinblue SAS, 7 rue de Madrid, 75008 Paris, Frankreich) übermittelt und gespeichert. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (Vertragsanbahnung) bzw. Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse). Die Daten werden gelöscht, sobald die Anfrage abschließend bearbeitet wurde." },
        { _key: "ds4", title: "4. Content Management System", content: "Für die Verwaltung von Website-Inhalten nutzen wir Sanity (Sanity Inc., 548 Market St PMB 49607, San Francisco, CA 94104, USA). Sanity ist zertifiziert nach dem EU-US Data Privacy Framework. Die Inhalte der Website werden über die Sanity API abgerufen. Dabei werden keine personenbezogenen Daten der Website-Besucher an Sanity übermittelt." },
        { _key: "ds5", title: "5. Cookies und Analyse-Tools", content: "Für die Verwaltung Ihrer Einwilligung zu Cookies setzen wir den Consent-Management-Dienst Cookiebot ein (Anbieter: Cybot A/S, Havnegade 39, 1058 Kopenhagen, Dänemark). Cookiebot blockiert Analyse- und Marketing-Cookies, bis Sie aktiv einwilligen.\n\nCookiebot setzt dazu ein technisch notwendiges Cookie:\n— CookieConsent: speichert Ihre Einwilligungseinstellungen. Speicherdauer: 12 Monate. Rechtsgrundlage: § 25 Abs. 2 Nr. 2 TTDSG (unbedingt erforderlich für den ausdrücklich gewünschten Telemediendienst), keine Einwilligung erforderlich.\n\nZur Messung und Analyse der Nutzung binden wir — nach Ihrer Einwilligung — Google Analytics 4 ein. Anbieter ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Google Analytics 4 wird erst geladen, nachdem Sie über Cookiebot in die Analyse-Cookies eingewilligt haben. In diesem Fall werden folgende Cookies gesetzt:\n\n— _ga: dient zur Unterscheidung einzelner Besucher. Speicherdauer: 24 Monate.\n— _ga_MZNP1LYCPH: speichert Session-Informationen zur aktuellen Property. Speicherdauer: 24 Monate.\n\nZweck: statistische Auswertung der Website-Nutzung zur Verbesserung des Angebots. Rechtsgrundlage ist Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO in Verbindung mit § 25 Abs. 1 TTDSG.\n\nSie können Ihre Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen oder anpassen — entweder über den Link \"Cookie-Einstellungen\" im Footer dieser Seite oder durch Löschen der Cookies in Ihrem Browser.\n\nIm Rahmen der Verarbeitung können Daten an Google LLC in den USA übermittelt werden. Google LLC ist zertifiziert nach dem EU-US Data Privacy Framework." },
        { _key: "ds6", title: "6. Ihre Rechte", content: "Sie haben gegenüber uns folgende Rechte:\n\n— Recht auf Auskunft (Art. 15 DSGVO)\n— Recht auf Berichtigung (Art. 16 DSGVO)\n— Recht auf Löschung (Art. 17 DSGVO)\n— Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO)\n— Recht auf Datenübertragbarkeit (Art. 20 DSGVO)\n— Recht auf Widerspruch gegen die Verarbeitung (Art. 21 DSGVO)\n\nSie haben zudem das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Die zuständige Aufsichtsbehörde für Berlin ist der Berliner Beauftragte für Datenschutz und Informationsfreiheit, Friedrichstr. 219, 10969 Berlin." },
        { _key: "ds7", title: "7. Aktualität und Änderung dieser Datenschutzerklärung", content: "Diese Datenschutzerklärung ist aktuell gültig und hat den Stand April 2026. Durch die Weiterentwicklung unserer Website oder aufgrund geänderter gesetzlicher Vorgaben kann es notwendig werden, diese Datenschutzerklärung zu ändern." },
      ],
    });

    // ─── kontaktPage erweitern ────────────────────────────────────────────────
    await client.createOrReplace({
      _id: "kontaktPage",
      _type: "kontaktPage",
      heroTitle: "Präzision beginnt beim ersten Gespräch.",
      contactName: "Thomas Müller",
      contactRole: "Leiter Kundenerfolg",
      contactText: "Wir verstehen, dass im Gutachterwesen jedes Detail zählt. Unser Team steht Ihnen zur Seite.",
      trustItems: [
        { _key: "k1", icon: "verified_user", title: "DSGVO-konform", description: "Alle Daten werden ausschließlich auf deutschen Servern verarbeitet." },
        { _key: "k2", icon: "timer", title: "Reaktionszeit", description: "Rückmeldung innerhalb von 24 Stunden an Werktagen." },
        { _key: "k3", icon: "map", title: "Standort Berlin", description: "Technologie entwickelt in Deutschland für den lokalen Markt." },
      ],
    });

    // ─── ablaufPage ───────────────────────────────────────────────────────────
    await client.createOrReplace({
      _id: "ablaufPage",
      _type: "ablaufPage",
      heroLabel: "Implementierung",
      heroTitle: "Vom Erstkontakt zur fertigen",
      heroTitleHighlight: "Expertise.",
      heroSubtext: "Effizienz beginnt bei der Einführung. Wir haben einen strukturierten Prozess entwickelt, der Ihre bestehenden Workflows respektiert und digital transformiert.",
      steps: [
        { _key: "step1", number: "01", title: "Anfrage", description: "Wir analysieren Ihren aktuellen Bedarf und prüfen die Kompatibilität Ihrer Datenstruktur mit unserer KI-Engine.", items: ["Erstgespräch & Bedarfsanalyse", "Daten-Checkup"] },
        { _key: "step2", number: "02", title: "Onboarding", description: "Integration der Schnittstellen und Training Ihres Teams auf die spezifischen Module Ihres Fachbereichs.", items: ["Setup & Integration", "Live-Schulung via Web-App"] },
        { _key: "step3", number: "03", title: "Loslegen", description: "Ab Tag 1 profitieren Sie von automatisierten Gutachten-Entwürfen und digitaler Beweissicherung.", items: ["Voller Funktionsumfang", "Support & Optimierung"] },
      ],
      timeline: [
        { _key: "t1", day: "0", label: "Tag 0", sublabel: "Kick-off Meeting", isRocket: false },
        { _key: "t2", day: "7", label: "Tag 1", sublabel: "Systemkonfiguration", isRocket: false },
        { _key: "t3", day: "14", label: "Ab Tag 1", sublabel: "Mitarbeiter-Training", isRocket: false },
        { _key: "t4", day: "", label: "Laufend", sublabel: "Skalierung & Updates", isRocket: true },
      ],
      trustItems: [
        { _key: "tr1", icon: "security", title: "Sicherheit & Datenschutz", description: "Ihre Daten verlassen niemals deutschen Boden. Unsere Server sind ISO 27001 zertifiziert und vollständig DSGVO-konform." },
        { _key: "tr2", icon: "settings_input_component", title: "Technische Integration", description: "Dank unserer modernen REST-API lässt sich gutachten-ai.de nahtlos in Ihre bestehende Branchensoftware integrieren." },
      ],
      ctaTitle: "Bereit für den digitalen Vorsprung?",
      ctaSubtext: "Sichern Sie sich jetzt ein unverbindliches Beratungsgespräch und erfahren Sie, wie wir Ihren Arbeitsalltag revolutionieren können.",
      ctaPrimaryButton: "Kostenloses Gespräch buchen",
      ctaSecondaryButton: "Funktionen ansehen",
    });

    // ─── funktionenPage ───────────────────────────────────────────────────────
    await client.createOrReplace({
      _id: "funktionenPage",
      _type: "funktionenPage",
      heroTitle: "Präzise Analysen. Rechtssichere Dokumentation.",
      heroSubtext: "Alle Werkzeuge für Bausachverständige — vom Beweisbeschluss bis zum fertigen Gutachten.",
      ctaText: "Zugang zum Gutachten Assistenten anfragen",
      features: [
        { _key: "f1", icon: "folder_open", title: "Fallverwaltung", description: "Alle Vorgänge strukturiert an einem Ort: Akte, Beweisbeschluss, Ortstermin und Gutachten sind als eigene Bereiche eines Falls organisiert.", example: "Ein Fall enthält Verfahrensdaten, alle Parteien, Kostenvorschuss und den vollständigen Beweisbeschluss — alles abrufbar mit einem Klick.", imageSrc: "/raumplan-feature.webp", imageAlt: "Grundriss-Übersicht — Fallverwaltung", reverse: false },
        { _key: "f2", icon: "inventory_2", title: "Digitale Akte", description: "Fotos, PDFs und Unterlagen werden fallbezogen abgelegt und sind nach Kategorie filterbar.", example: "Unterlagen nach Typ filtern: Grundrisse, Gutachten, Rechnungen oder Schriftverkehr — immer sofort auffindbar.", imageSrc: "/Konstruktionsdetail-feature.webp", imageAlt: "Konstruktionsdetail — digitale Akte", reverse: true },
        { _key: "f3", icon: "sim_card_download", title: "Gutachten-Export", description: "Das fertige Gutachten wird direkt aus der App als PDF oder Word-Dokument exportiert — strukturiert nach Beweisfragen.", example: "Export auf Knopfdruck: vollständiges Gutachten als DOCX oder als PDF zur Einreichung beim Gericht.", imageSrc: "/Pruefbericht-feature.webp", imageAlt: "Prüfbericht-Formular — Gutachten-Export", reverse: false },
        { _key: "f4", icon: "quiz", title: "Beweisfragen-Editor", description: "Bis zu 18 Beweisfragen pro Fall — jede mit eigenem Editor für Behauptung, Hinweis und Feststellungen.", example: "BF1 mit Unterbeweisfragen a–f: jede Feststellung separat erfasst und beim Export korrekt strukturiert.", imageSrc: "/Konstruktionsdetail-feature.webp", imageAlt: "Baufortschritt-Report — Beweisfragen-Editor", reverse: true },
        { _key: "f5", icon: "receipt_long", title: "Rechnungen", description: "Automatisierte Erstellung von JVEG-konformen Rechnungen oder Honorarberechnungen nach Zeitaufwand.", example: "Ein-Klick-Erstellung der Gesamtabrechnung nach Abschluss des Gutachtens inkl. aller Nebenkosten.", imageSrc: "/Rechnung-feature.webp", imageAlt: "Rechnungs-Dashboard — JVEG-konforme Honorarabrechnung", reverse: false },
      ],
      faq: [
        { _key: "q1", question: "Sind meine Daten sicher?", answer: "Ja. Alle Daten werden auf deutschen Servern verarbeitet und sind vollständig DSGVO-konform verschlüsselt." },
        { _key: "q2", question: "Ersetzt die KI den menschlichen Gutachter?", answer: "Nein. Die KI dient als Assistenzsystem, das zeitaufwendige Recherche- und Schreibarbeiten übernimmt, damit Sie sich auf die fachliche Bewertung konzentrieren können." },
        { _key: "q3", question: "Wie aktuell sind die DIN-Normen?", answer: "Unsere Datenbank wird kontinuierlich aktualisiert, um stets den neuesten Stand der Technik abzubilden." },
      ],
    });

    // ─── Blog-Posts (unverändert) ─────────────────────────────────────────────
    await client.createOrReplace({ _id: "post-zeitersparnis", _type: "post",
      title: "Zeitersparnis für Bausachverständige: Wo KI 30–60 Prozent Bearbeitungszeit spart – und wo nicht",
      slug: { _type: "slug", current: "zeitersparnis-bausachverstaendige" },
      category: "Praxis",
      publishedAt: "2026-05-16",
      excerpt: "Bausachverständige erzielen mit KI-Software realistische Zeitersparnis-Bandbreiten von 20 bis 35 Prozent pro Gutachten. Bei einzelnen Textaufgaben sind es 30 bis 60 Prozent, beim Ortstermin 0 bis 10 Prozent. Mit Datenlage und Praxisbeispielen.",
      body: [
        b("ze0","normal","Bausachverständige erzielen mit KI-Software realistische Zeitersparnis-Bandbreiten von 20 bis 35 Prozent pro Gutachten. Wer höhere Versprechen liest, sollte skeptisch werden. Die Wahrheit ist differenzierter: Bei einzelnen Tätigkeiten spart KI 30 bis 60 Prozent, bei der gesamten Gutachten-Produktion 20 bis 35 Prozent, beim Ortstermin selbst 0 bis 10 Prozent."),
        b("ze1","h2","Warum Verfahrensdauer und Gutachten-Erstellung Gegenstand der Justizpolitik sind"),
        b("ze2","normal","Zivilverfahren dauern länger, die Anzahl der Sachverständigen sinkt, Wartezeiten auf Gutachten steigen. Das Statistische Bundesamt dokumentiert für 2024 eine durchschnittliche Verfahrensdauer bei Landgerichten von 17,5 Monaten bis zum streitigen Urteil – eine Steigerung von 4,8 Prozent gegenüber 2023. In jedem zweiten lang dauernden Verfahren ist der Sachverständigenbeweis erforderlich, der durchschnittlich rund 40 Prozent der Verfahrensdauer ausmacht. Wer am Sachverständigenbeweis Zeit spart, beschleunigt das Verfahren erheblich."),
        b("ze3","h2","Rückläufige Anzahl öffentlich bestellter Sachverständiger"),
        b("ze4","normal","Der BVS dokumentiert seit Jahren rückläufige Zahlen öffentlich bestellter und vereidigter Sachverständiger und Wartezeiten von über einem Jahr auf Gutachten. Der demografische Wandel verstärkt das Problem: viele erfahrene Sachverständige gehen in den Ruhestand, junge Bewerber bleiben aus. KI-Effizienz ist kein Luxus, sondern Voraussetzung dafür, dass die verbleibenden Sachverständigen mehr Aufträge bewältigen."),
        b("ze5","h2","Wo Zeit im Sachverständigenbüro tatsächlich verloren geht"),
        b("ze6","normal","Eine grobe Aufschlüsselung der Bearbeitungszeit pro Gutachten: 5 bis 10 Prozent Beweisbeschluss-Lektüre und Akteneinsicht, 15 bis 25 Prozent Ortstermin (inkl. An- und Abreise), 10 bis 15 Prozent Befund und Messprotokolle, 40 bis 55 Prozent Reinschrift und Strukturierung, 5 bis 10 Prozent JVEG-Abrechnung. Der größte Hebel ist die Reinschrift – mehr als die Hälfte der Bearbeitungszeit. Wer hier 30 Prozent spart, spart erheblich am Gesamtaufwand."),
        b("ze7","h2","Wo KI nachweislich Zeit spart"),
        b("ze8","h3","Diktat-zu-Text mit Fachsprache"),
        b("ze9","normal","Diktat-zu-Text-Funktionen sind die effizienteste KI-Anwendung im Sachverständigenbüro. Moderne Modelle erreichen mit Fachsprache-Adaption über 95 Prozent Wortgenauigkeit für Bau-Vokabular. Wer bisher 200 Wörter pro Minute denken, aber nur 40 tippen kann, gewinnt das Fünffache an Output. Beim Ortstermin diktiert die Sachverständige Befunde direkt ins Handy; in der Reinschrift sind die Befunde bereits transkribiert verfügbar."),
        b("ze10","h3","Aktenanalyse mit Volltextsuche"),
        b("ze11","normal","Semantische Volltextsuche findet relevante Stellen in 240 Seiten Akte in Sekunden – manuell dauert das Stunden. Wer nach \"Maßnahmen zur Abdichtung\" sucht, findet auch Stellen mit \"Sperrputz\" oder \"Dichtschlämme\", ohne die exakten Begriffe zu kennen."),
        b("ze12","h3","Vorlagen und Textbausteine"),
        b("ze13","normal","Wiederkehrende Standard-Formulierungen – zur Methodik der Feuchtemessung, zur Beweisfrage-Beantwortung, zum Disclaimer – laufen über Textbausteine. KI personalisiert die Bausteine auf den konkreten Fall und ergänzt Aktenzeichen und Parteibezeichnungen automatisch."),
        b("ze14","h3","Normen-Recherche"),
        b("ze15","normal","Semantische Normenrecherche findet zu einem Schadensbild die passenden DIN-Normen und WTA-Merkblätter. Was früher 30 bis 60 Minuten Lese-Recherche kostete, ist in 5 bis 10 Minuten erledigt."),
        b("ze16","h3","Kosten- und Stundenerfassung"),
        b("ze17","normal","Zeiterfassung läuft während der Bearbeitung im Hintergrund mit, die JVEG-Abrechnung nach § 9 JVEG berechnet sich am Ende automatisch. Schreibgebühr und Foto-Pauschale werden aus den tatsächlichen Daten abgeleitet."),
        b("ze18","h2","Wo KI keine Zeit spart oder Risiken birgt"),
        b("ze19","normal","KI ersetzt nicht die fachliche Würdigung, die Schadensbewertung im Streit, die rechtliche Auslegung des Beweisbeschlusses. Wer der KI vertraut ohne nachzuprüfen, riskiert Hallucinationen. Beim Ortstermin spart KI fast nichts: die Anfahrt bleibt gleich, die Begehung dauert gleich lang, die physische Probenahme kann nicht delegiert werden. Auch bei der Beurteilung kontroverser Fragen – etwa der Abgrenzung zwischen baulicher und nutzungsbedingter Schimmelursache – bringt KI nichts."),
        b("ze20","h2","Realistische Zeitersparnis-Bandbreiten"),
        b("ze21","normal","Drei Bandbreiten haben sich in der Praxis etabliert. Bei reinen Textaufgaben (Reinschrift, Strukturierung, Standardformulierungen): 30 bis 60 Prozent Zeitersparnis. Bei der gesamten Gutachten-Produktion: 20 bis 35 Prozent. Beim Ortstermin selbst: 0 bis 10 Prozent. KI verschiebt Wertschöpfung von Schreibarbeit zur Beurteilung – Sachverständige werden zu Begutachterinnen und Beurteilenden, die weniger Zeit auf Routinetätigkeiten und mehr auf die fachlich anspruchsvolle Würdigung verwenden."),
        b("ze22","h2","Fazit"),
        b("ze23","normal","Bausachverständige sparen mit KI realistisch 20 bis 35 Prozent Bearbeitungszeit pro Gutachten. Die größten Hebel sind Diktat, Aktenanalyse, Textbausteine und automatisierte JVEG-Abrechnung. KI ersetzt nicht die fachliche Würdigung, sondern verschiebt den Arbeitsschwerpunkt auf die anspruchsvolle Beurteilung. Angesichts rückläufiger Sachverständigen-Zahlen und steigender Verfahrensdauer ist KI-Effizienz kein Luxus, sondern Voraussetzung für die Funktionsfähigkeit der Justiz."),
      ] });
    await client.createOrReplace({ _id: "post-din-normen-ki", _type: "post",
      title: "DIN-Normen im Baugutachten: Welche Normen Sachverständige zitieren – und wie KI bei der Recherche hilft",
      slug: { _type: "slug", current: "din-normen-ki" },
      category: "Recht & Normen",
      publishedAt: "2026-05-16",
      excerpt: "DIN-Normen im Baugutachten konkretisieren die anerkannten Regeln der Technik. Welche Normen wann anwendbar sind, welche Fassung gilt und wie KI-gestützte Software bei der Recherche unterstützt – ein systematischer Überblick über DIN 4108, DIN 18533, DIN 4109 und DIN V 18599.",
      body: [
        b("dn0","normal","DIN-Normen im Baugutachten konkretisieren die anerkannten Regeln der Technik. Wer als Bausachverständiger ein Gutachten schreibt, zitiert regelmäßig DIN-Normen als Maßstab für die Beurteilung von Mängeln und Schäden. Welche Normen wann anwendbar sind, welche Fassung gilt und wie KI-gestützte Software bei der Recherche unterstützt – das klärt dieser Beitrag systematisch."),
        b("dn1","h2","Warum DIN-Normen für Bausachverständige rechtlich verbindlich sind"),
        b("dn2","normal","DIN-Normen sind grundsätzlich keine Rechtsnormen, sondern privatrechtliche Empfehlungen des Deutschen Instituts für Normung. Sie entfalten Bindungswirkung erst, wenn sie durch Gesetz oder Verordnung in Bezug genommen werden – etwa DIN V 18599 im Gebäudeenergiegesetz – oder vertraglich vereinbart sind. Im Gerichtsalltag haben sie dennoch einen hohen Stellenwert, weil sie regelmäßig die anerkannten Regeln der Technik wiedergeben. Wo eine DIN-Norm den allgemein anerkannten technischen Standard zutreffend abbildet, wird der Sachverständige ihre Einhaltung als Mindeststandard verlangen."),
        b("dn3","h2","Anerkannte Regeln der Technik, Stand der Technik, Stand von Wissenschaft und Technik"),
        b("dn4","normal","Drei Begriffe sind sauber zu unterscheiden. Anerkannte Regeln der Technik sind nach ständiger BGH-Rechtsprechung wissenschaftlich richtige Verfahren, die in der Praxis erprobt sind und sich bewährt haben (BGH VII ZR 184/97). Stand der Technik geht darüber hinaus und umfasst auch noch nicht allgemein anerkannte, aber technisch ausgereifte Verfahren. Stand von Wissenschaft und Technik bezeichnet den jeweils aktuellsten Forschungsstand. Der Bausachverständige sollte im Gutachten ausdrücklich angeben, welchen Maßstab er anlegt."),
        b("dn5","h2","Die wichtigsten DIN-Normen im Baugutachten"),
        b("dn6","normal","Die DIN 4108-Reihe und DIN 18533 zählen zu den meistzitierten DIN-Normen im Baugutachten zu Feuchteschäden. Daneben sind DIN 4109 (Schallschutz), DIN EN 13501 (Brandverhalten) und seit 2024 DIN V 18599 (energetische Bewertung) zentral."),
        b("dn7","h3","DIN 4108 – Wärme- und Feuchteschutz"),
        b("dn8","normal","Die DIN 4108-Reihe regelt den Wärmeschutz und Feuchteschutz von Gebäuden. Wichtige Teile: DIN 4108-2:2013-02 Mindestanforderungen Wärmeschutz, DIN 4108-3:2024-03 klimabedingter Feuchteschutz (Glaser-Verfahren), DIN 4108-4:2020-11 Bemessungswerte, DIN 4108-7:2011-01 Luftdichtheit, DIN/TS 4108-8 Schimmelvermeidung. DIN 4108 Beiblatt 2:2019-06 mit Berichtigung 1:2025-02 enthält typische Wärmebrücken-Detailbeispiele."),
        b("dn9","h3","DIN 18533, 18531, 18534 – Abdichtungen"),
        b("dn10","normal","Die DIN 18533-Familie löste 2017 die alte DIN 18195 ab. DIN 18533-1:2017-07 regelt die Abdichtung erdberührter Bauteile, DIN 18531 die Dachabdichtung, DIN 18534 die Abdichtung von Innenräumen (Bäder, Küche). Wichtig ist die Differenzierung nach Wassereinwirkungsklasse (W1 bis W4) – sie bestimmt das erforderliche Abdichtungssystem."),
        b("dn11","h3","DIN 4109 – Schallschutz"),
        b("dn12","normal","DIN 4109-1:2018-01 regelt den Mindestschallschutz von Gebäuden. Die Norm gibt Mindestanforderungen vor, keinen erhöhten Schallschutz. Bei Schallschutz-Gutachten unterscheidet der Sachverständige zwischen gesetzlicher Mindestanforderung (DIN 4109-1) und vereinbartem erhöhtem Schutzniveau (z. B. nach VDI 4100 oder DIN 4109-5)."),
        b("dn13","h3","DIN EN 13501 – Brandverhalten"),
        b("dn14","normal","DIN EN 13501-1 klassifiziert das Brandverhalten von Bauprodukten europaweit einheitlich. Die Klassen reichen von A1 (nicht brennbar) über B (schwer entflammbar) bis F (leicht entflammbar). Bei Fassaden-Gutachten nach Bränden wird der Sachverständige regelmäßig auf diese Klassifizierung Bezug nehmen, ergänzt um die landesrechtlichen Bauordnungen."),
        b("dn15","h3","DIN V 18599 – Energetische Bewertung (GEG)"),
        b("dn16","normal","DIN 4108-6 wurde für öffentlich-rechtliche Nachweise und Energieausweise zum 01.01.2024 durch DIN V 18599 abgelöst. Die Vornorm bilanziert den Energiebedarf für Heizung, Trinkwarmwasser, Lüftung, Kühlung und Beleuchtung. Für energetische Sanierungsgutachten ist sie heute der zentrale Referenzpunkt; DIN 4108-6 darf für GEG-Nachweise nicht mehr verwendet werden."),
        b("dn17","h2","Welche Normfassung gilt – Baujahr und anerkannte Regeln des Baujahreszeitraums"),
        b("dn18","normal","Maßstab für Mängel ist nach ständiger Rechtsprechung die zur Bauzeit geltende Fassung der DIN-Norm (BGH V ZR 182/12, Urteil vom 04.10.2013). Ein Altbau aus 1985 wird nicht an DIN 4108-3:2024 gemessen, sondern an der damals geltenden Fassung. Bei Neubauten und wesentlichen Umbauten gilt die aktuelle Normfassung zum Zeitpunkt der Bauausführung. Im Gutachten wird die zitierte Normfassung mit Ausgabedatum benannt (Beispiel: \"DIN 4108-3:2024-03\")."),
        b("dn19","h2","Wie KI bei der Normenrecherche unterstützt – und was sie nicht ersetzt"),
        b("dn20","normal","KI-gestützte Software kann DIN-Normen-Recherche beschleunigen, ersetzt aber die sachverständige Würdigung nicht. Drei sinnvolle Anwendungsfälle: Erstens semantische Suche – die KI findet zu einem Schadensbild die thematisch passenden Normen und WTA-Merkblätter. Zweitens Versionsvergleich – die KI markiert Änderungen zwischen alter und neuer Fassung. Drittens Querverweis-Erkennung – die KI extrahiert die Verweiskette und schlägt weitere zu prüfende Normen vor. Die Beurteilung, ob eine Norm im konkreten Fall einschlägig ist, bleibt sachverständige Tätigkeit."),
        b("dn21","h2","Häufige Fehler beim Normenzitat im Baugutachten"),
        b("dn22","normal","Wiederkehrende Fehler: Erstens Zitat zurückgezogener Normen ohne Hinweis auf den Ersatz – DIN 4108-6 wurde 2024 durch DIN V 18599 ersetzt. Zweitens Verwechslung von U-Wert und Wärmedurchlasswiderstand. Drittens fehlender Verweis auf den Anwendungsbereich: DIN 18533 gilt für erdberührte Bauteile, nicht für Dächer. Viertens Zitat ohne Fassungsdatum. Fünftens Vermengung von Mindest- und erhöhtem Schallschutz."),
        b("dn23","h2","Fazit"),
        b("dn24","normal","DIN-Normen sind das wichtigste Bezugssystem für Bausachverständige bei der Beurteilung von Mängeln und Schäden. Die Auswahl der einschlägigen Norm und ihrer Fassung folgt dem Anwendungsbereich und der Bauzeit. KI-gestützte Recherche-Tools sparen Zeit bei der semantischen Suche und beim Versionsvergleich, ersetzen aber die fachliche Würdigung nicht. Wer sauber zitiert, gibt Norm, Teil, Fassungsdatum und Anwendungsbereich an."),
      ] });
    await client.createOrReplace({ _id: "post-ki-gutachten-2025", _type: "post",
      title: "KI im Gutachten 2026: Was Sachverständige rechtlich, technisch und praktisch wissen müssen",
      slug: { _type: "slug", current: "ki-gutachten-2025" },
      category: "Technologie",
      publishedAt: "2026-05-16",
      excerpt: "KI im Gutachten unterstützt Sachverständige bei Aktenanalyse, Normenrecherche und Gutachten-Erstellung. 2026 ist das Jahr, in dem KI im Sachverständigenwesen vom Pilotprojekt zur Praxisanwendung wird. Rechtsrahmen, Anwendungsfelder und Ausblick.",
      body: [
        b("ki0","normal","KI im Gutachten unterstützt Sachverständige bei Aktenanalyse, Normenrecherche und Gutachten-Erstellung. Wer KI im Sachverständigenwesen einsetzt, beachtet § 407a ZPO, den EU AI Act und die DSGVO. Dieser Pillar-Beitrag liefert den Überblick: was KI leistet, was sie nicht ersetzt, welche Rechtsregeln gelten."),
        b("ki1","h2","Was KI im Gutachten-Kontext leistet – und was nicht"),
        b("ki2","normal","KI im Gutachten-Kontext bezeichnet vier Kategorien: generative Sprachmodelle (LLMs wie Mistral, GPT, Claude) für Textproduktion und Strukturierung; Bilderkennungsmodelle für Schadensbildklassifikation; Retrieval-Augmented Generation (RAG) für die strukturierte Abfrage von Normendatenbanken; Workflow-Automatisierung für Akten, Termine, Abrechnung. KI-Gutachten ersetzen nicht den Sachverständigen – sie verlagern Routinearbeit. Die fachliche Beurteilung bleibt. Der Gesetzgeber hat dies durch § 407a Abs. 1 ZPO klar geregelt: Vollständige Delegation an KI ist unzulässig."),
        b("ki3","h2","Rechtsrahmen für KI im Sachverständigenwesen"),
        b("ki4","h3","Verfahrensrecht – §§ 404a, 407a, 411 ZPO"),
        b("ki5","normal","§ 404a ZPO regelt die Leitung der Sachverständigentätigkeit durch das Gericht – der Sachverständige ist weisungsgebundener Berater. § 407a ZPO normiert die Pflicht zur eigenverantwortlichen Begutachtung – KI darf unterstützen, aber nicht ersetzen. § 411 Abs. 4 ZPO verlangt schriftliche Ergänzungsfragen, die fachlich verantwortet werden."),
        b("ki6","h3","EU AI Act und Anhang III Nr. 8"),
        b("ki7","normal","Die Verordnung (EU) 2024/1689 hat die KI-Anwendung in der Justiz geregelt – aber nicht jede Gutachten-KI fällt unter Anhang III Nr. 8 lit. a. Eine Gutachten-KI als Hilfsmittel des Sachverständigen fällt nach Erwägungsgrund 61 regelmäßig nicht unter die Hochrisiko-Vorschrift. Der Sachverständige ist nach OLG Hamm 32 W 7/16 keine Justizbehörde."),
        b("ki8","h3","DSGVO und Berufsrecht"),
        b("ki9","normal","DSGVO-konformer Einsatz erfordert AV-Verträge nach Artikel 28, Verarbeitungsverzeichnis nach Artikel 30, bei besonderen Kategorien auch DSFA nach Artikel 35. Die Verschwiegenheitspflicht gilt: sensible Daten dürfen nicht ungeschützt an Cloud-Dienstleister außerhalb der EU übermittelt werden."),
        b("ki10","h3","JVEG-Vergütung bei KI-Einsatz"),
        b("ki11","normal","Die JVEG-Vergütung bleibt zeitabhängig – gespart wird beim eigenen Stundenaufwand, nicht beim Stundensatz. Wer 10 statt 16 Stunden für ein Gutachten braucht, rechnet 10 Stunden ab. Die Effizienz wird durch höheren Durchsatz monetarisiert."),
        b("ki12","h2","Anwendungsfelder im Bausachverständigen-Alltag"),
        b("ki13","h3","Beweisbeschluss-Analyse"),
        b("ki14","normal","KI extrahiert Beweisfragen, identifiziert Anknüpfungstatsachen, prüft gegen die Aktenlage. Mehrfachfragen werden zur Aufgliederung markiert."),
        b("ki15","h3","Akten- und Bildauswertung"),
        b("ki16","normal","Volltextsuche über 240 Seiten Akte in Sekunden. Bilderkennung klassifiziert Schadensbilder (Salzausblühung, Schimmel, Putzabplatzung). Messprotokolle werden automatisch in Tabellen überführt."),
        b("ki17","h3","Normenrecherche"),
        b("ki18","normal","Semantische Suche findet zu einem Schadensbild die passenden DIN-Normen und WTA-Merkblätter, ohne dass exakte Begriffe bekannt sein müssen."),
        b("ki19","h3","Diktat und Textproduktion"),
        b("ki20","normal","Diktat-zu-Text mit Fachsprache-Adaption erreicht über 95 Prozent Wortgenauigkeit. Reinschrift wird um 30 bis 60 Prozent beschleunigt."),
        b("ki21","h3","JVEG-Abrechnung"),
        b("ki22","normal","Automatische Zeiterfassung, Plausibilitätsprüfung gegen JVEG-Sätze, fertige Honorarrechnung im PDF/A-Format für die Einreichung über das eBO."),
        b("ki23","h2","Was KI nicht ersetzt – Kernkompetenz des Sachverständigen"),
        b("ki24","normal","Fünf Tätigkeiten bleiben sachverständige Kerntätigkeit: die fachliche Würdigung am Ortstermin, die Schadensbewertung im Streit, die rechtliche Auslegung des Beweisbeschlusses, die persönliche Verantwortung nach § 407 ZPO – die Unterschrift ist nicht delegierbar – und die mündliche Erläuterung in der Verhandlung nach § 411 Abs. 3 ZPO."),
        b("ki25","h2","Praxisbeispiel: 90-Minuten-Erstanalyse eines Bauschadens-Falls"),
        b("ki26","normal","Bauschaden mit drei Beweisfragen, 240 Aktenseiten, 80 Fotos. Manueller Workflow ohne KI: 12 bis 16 Stunden bis zum Erstentwurf. KI-gestützter Workflow: 6 bis 8 Stunden. Die Erstanalyse – Beweisfragen extrahieren, Akte querlesen, erste Hypothesen formulieren, Ortstermin vorbereiten – lässt sich in 90 Minuten erledigen."),
        b("ki27","h2","Akzeptanz der Justiz und Transparenzpflicht"),
        b("ki28","normal","Gerichte akzeptieren KI-gestützte Gutachten zunehmend, fordern aber Transparenz. Empfohlene Methodenangabe im Gutachten: \"Bei der Strukturierung der Aktenanalyse wurden Volltextsuche und KI-gestützte Hervorhebung eingesetzt. Sämtliche fachliche Schlussfolgerungen wurden vom Unterzeichner persönlich verantwortet.\" Diese Praxis folgt aus § 407a ZPO."),
        b("ki29","h2","Ausblick – was bis 2027 erwartet wird"),
        b("ki30","normal","Drei Entwicklungen: Erstens Standardisierung der Schnittstellen zwischen Gutachten-KI und ERV (eBO, XJustiz). Zweitens KI-Markt-Integrationsgesetz in Deutschland zur Umsetzung des EU AI Act – erwartet im ersten Halbjahr 2027. Drittens nächste JVEG-Anpassung voraussichtlich 2028."),
        b("ki31","h2","Fazit"),
        b("ki32","normal","KI im Gutachten 2026 ist Praxisanwendung, kein Pilotprojekt. Der Rechtsrahmen aus § 407a ZPO, EU AI Act und DSGVO setzt klare Grenzen: KI unterstützt, ersetzt aber nicht. Realistische Zeitersparnis: 20 bis 35 Prozent bei der gesamten Gutachten-Produktion, 30 bis 60 Prozent bei reinen Textaufgaben. Die Justiz akzeptiert die Praxis bei angemessener Transparenz."),
      ] });
    await client.createOrReplace({ _id: "post-jveg-honorar-berechnen", _type: "post",
      title: "JVEG-Honorar berechnen: Honorargruppen, Nebenkosten und Fristen für Sachverständige (Stand 2026)",
      slug: { _type: "slug", current: "jveg-honorar-berechnen" },
      category: "Abrechnung",
      publishedAt: "2026-05-16",
      excerpt: "JVEG-Honorar berechnen nach § 9 JVEG mit den ab 01.06.2025 angehobenen Stundensätzen. Honorargruppen 2, 3 und 4 für Bausachverständige, Nebenkosten nach § 7 und § 12, Drei-Monats-Frist nach § 2 JVEG – mit vollständigem Rechenbeispiel.",
      body: [
        b("jv0","normal","Das JVEG-Honorar berechnen Sachverständige nach § 9 JVEG in Verbindung mit Anlage 1 JVEG. Wer als gerichtlich beauftragter Sachverständiger ein Gutachten erstellt, rechnet sein Honorar zwingend nach dem Justizvergütungs- und -entschädigungsgesetz ab. Die Stundensätze sind seit dem 01.06.2025 in angepasster Form anwendbar."),
        b("jv1","h2","Was regelt das JVEG für gerichtlich beauftragte Sachverständige"),
        b("jv2","normal","Das JVEG gilt seit dem 01.07.2004 und regelt die Vergütung von Sachverständigen, wenn das Gericht sie nach § 404 ZPO heranzieht – etwa für ein Sachverständigengutachten in einem Zivilprozess oder in einem selbständigen Beweisverfahren nach § 485 ZPO. Im Privatauftrag können Sachverständige ihr Honorar frei vereinbaren. Sobald eine gerichtliche Beauftragung vorliegt, greift das JVEG zwingend. Eine abweichende Honorarvereinbarung ist nur unter den engen Voraussetzungen des § 13 JVEG zulässig."),
        b("jv3","h2","JVEG-Honorargruppen ab 01.06.2025 im Überblick"),
        b("jv4","normal","Die JVEG-Honorargruppen wurden zum 01.06.2025 um 15 Euro pro Stunde angehoben (Kostenrechtsänderungsgesetz 2025, BGBl. 2024 I Nr. 206). Für das Bauwesen gilt: Honorargruppe 2 für handwerklich-technische Ausführung mit 70 Euro pro Stunde, Honorargruppe 3 für Garten- und Landschaftsbau mit 75 Euro pro Stunde, Honorargruppe 4 für Bauwesen-Planung sowie Schadensfeststellung und Bewertung mit 80 Euro pro Stunde."),
        b("jv5","h3","Honorargruppe 2 – Bauwesen handwerklich-technisch"),
        b("jv6","normal","Honorargruppe 2 umfasst Gutachten zu handwerklich-technischen Bauleistungen. Typische Aufgaben: Begutachtungen zu Mängeln einzelner Gewerke wie Putz, Estrich, Fliesen, Trockenbau, Dach- oder Fassadenarbeiten. Der Stundensatz beträgt seit 01.06.2025 70 Euro netto. Entscheidend ist, dass die Begutachtung sich auf die handwerkliche Ausführung bezieht und keine Planungs- oder Bewertungsleistung erbracht wird."),
        b("jv7","h3","Honorargruppe 3 – Garten- und Landschaftsbau"),
        b("jv8","normal","Honorargruppe 3 ist spezifisch für Sachverständige des Garten- und Landschaftsbaus einschließlich Sportanlagenbau (75 Euro netto). Für den klassischen Hochbau-Bausachverständigen ist diese Honorargruppe nicht einschlägig."),
        b("jv9","h3","Honorargruppe 4 – Schadensfeststellung und Bewertung"),
        b("jv10","normal","Honorargruppe 4 ist die wichtigste Gruppe für öffentlich bestellte und vereidigte Bausachverständige. Sie erfasst Bauwesen-Planung, Schadensfeststellung, Schadensursachenermittlung und Bewertung (80 Euro netto). Ein Beweisbeschluss zur Feststellung von Schadensursachen oder zur Bewertung von Sanierungskosten führt zur Anwendung dieser Honorargruppe. Das betrifft die Mehrzahl aller gerichtlichen Bauschaden-Gutachten."),
        b("jv11","h2","Wie das Gericht die Honorargruppe nach Anlage 1 JVEG bestimmt"),
        b("jv12","normal","Die Zuordnung richtet sich nach § 9 Abs. 1 S. 2 JVEG nach der Entscheidung des Gerichts im Beweisbeschluss, nicht nach der tatsächlich erbrachten Leistung. Bei Leistungen auf mehreren Sachgebieten gilt nach § 9 Abs. 1 S. 4 JVEG die höchste Honorargruppe. Ist die Zuordnung unklar, sollte der Sachverständige unverzüglich nach § 407a Abs. 4 ZPO Rücksprache mit dem Gericht halten."),
        b("jv13","h2","JVEG-Nebenkosten nach § 7 und § 12"),
        b("jv14","normal","§ 12 JVEG regelt besondere Aufwendungen. Pro erforderliches Foto erstattet die Staatskasse 2 Euro für den ersten Abzug, 0,50 Euro für jeden weiteren. Die Schreibgebühr beträgt 0,90 Euro je angefangene 1.000 Anschläge. § 7 JVEG regelt sonstige Aufwendungen einschließlich Kopien: 0,50 Euro je Seite für die ersten 50 Kopien, 0,15 Euro für jede weitere. Farbkopien werden pauschal mit 2 Euro pro Seite erstattet. Postpauschale: 20 Prozent des Honorars, höchstens 15 Euro nach § 7 Abs. 2 S. 2 JVEG. Nebenkosten machen bei umfangreichen Gutachten 10 bis 20 Prozent des Gesamthonorars aus."),
        b("jv15","h2","JVEG-Honorar berechnen – vollständiges Rechenbeispiel"),
        b("jv16","normal","Beispiel: Honorargruppe 4, 25 Stunden, 22 erforderliche Fotos, 18.000 Anschläge Gutachtentext, 65 Kopien, 80 km Anfahrt. Honorar: 25 h × 80 Euro = 2.000 Euro. Fotos: 22 × 2 Euro = 44 Euro. Schreibgebühr: 18 × 0,90 Euro = 16,20 Euro. Kopien: 50 × 0,50 + 15 × 0,15 = 27,25 Euro. Fahrtkosten: 80 km × 0,42 Euro = 33,60 Euro. Postpauschale: gedeckelt auf 15 Euro. Zwischensumme netto: 2.136,05 Euro. Umsatzsteuer 19 Prozent: 405,85 Euro. Gesamtbetrag brutto: 2.541,90 Euro. Die Stundenzahl ist plausibel zu begründen – Zeiterfassung wird während der Bearbeitung geführt, nicht rekonstruiert."),
        b("jv17","h2","Frist zur Geltendmachung des JVEG-Honorars (§ 2 JVEG)"),
        b("jv18","normal","Die JVEG-Abrechnung muss binnen drei Monaten nach Abschluss der Tätigkeit beim Gericht eingehen, sonst erlischt der Anspruch nach § 2 JVEG. Beendigung der Tätigkeit ist regelmäßig die Übersendung des vollständigen Gutachtens. Empfehlung: Der Antrag wird unmittelbar nach Abschluss des Gutachtens gestellt, idealerweise gemeinsam mit der Übersendung des Schlussstücks."),
        b("jv19","h2","Abweichende Vergütung nach § 13 JVEG bei besonderer Schwierigkeit"),
        b("jv20","normal","§ 13 JVEG ermöglicht eine abweichende Vergütung bei drei Voraussetzungen: schriftliche Zustimmung der Parteien, Genehmigung des Gerichts, Nachweis der Notwendigkeit. Die Höchstgrenze liegt beim Doppelten des gesetzlichen Stundensatzes – in Honorargruppe 4 also bis zu 160 Euro pro Stunde. In der Praxis ist § 13 JVEG selten, eröffnet aber bei begründetem Anlass eine wertvolle Ausnahme."),
        b("jv21","h2","Häufige Fehler bei der JVEG-Abrechnung"),
        b("jv22","normal","Fünf wiederkehrende Fehler: Erstens versäumte Antragsfrist nach § 2 JVEG – der Anspruch erlischt endgültig. Zweitens falsche Honorargruppe – wer in Gruppe 2 statt Gruppe 4 abrechnet, verschenkt 10 Euro pro Stunde. Drittens fehlende oder rekonstruierte Zeitnachweise – Gerichte kürzen regelmäßig. Viertens vergessene Nebenkosten – Schreibgebühr und Foto-Pauschale werden oft übersehen. Fünftens nicht erforderliche Fotos – § 12 JVEG erstattet nur Fotos, die für das Gutachten erforderlich sind."),
        b("jv23","h2","Wie KI bei der JVEG-Abrechnung unterstützt"),
        b("jv24","normal","KI-gestützte Software automatisiert die JVEG-Abrechnung: Zeiterfassung läuft während der Bearbeitung mit Zuordnung zu Akte und Tätigkeit. Die Software erkennt anhand des Beweisbeschlusses die einschlägige Honorargruppe. Die Anzahl erforderlicher Fotos wird aus der Foto-Verwaltung übernommen, die Schreibgebühr berechnet sich aus den tatsächlichen Anschlägen. Eine Plausibilitätsprüfung warnt vor typischen Fehlern. Das System erzeugt eine fertige Honorarrechnung im PDF-Format für die elektronische Einreichung über das eBO."),
        b("jv25","h2","Fazit"),
        b("jv26","normal","Das JVEG-Honorar berechnen Sachverständige nach § 9 JVEG mit den ab 01.06.2025 angehobenen Stundensätzen von 70, 75 oder 80 Euro. Nebenkosten nach §§ 7 und 12 erhöhen das Gesamthonorar um 10 bis 20 Prozent. Die Drei-Monats-Frist nach § 2 JVEG ist zwingend. Wer systematisch arbeitet, Zeitnachweise sauber führt und KI-gestützte Abrechnungstools einsetzt, sichert sich das volle Honorar ohne Kürzungen."),
      ] });
    await client.createOrReplace({ _id: "post-feuchtigkeitsschaeden-gutachten", _type: "post",
      title: "Feuchtigkeitsschäden im Gutachten: Ursachenermittlung, Messverfahren und Sanierungsbewertung",
      slug: { _type: "slug", current: "feuchtigkeitsschaeden-gutachten" },
      category: "Fachthema",
      publishedAt: "2026-05-16",
      excerpt: "Feuchtigkeitsschäden im Gutachten erfordern systematische Ursachenermittlung nach DIN 4108-3 und DIN 18533. Schadensbilder erkennen, Messverfahren auswählen, Normen zuordnen, Sanierung bewerten – das systematische Vorgehen für Sachverständige.",
      body: [
        b("fs0","normal","Feuchtigkeitsschäden zählen zu den häufigsten Gutachtenanlässen im Bauwesen – und zu den fachlich anspruchsvollsten. Eine falsche Ursachenzuordnung führt zu falschen Sanierungsempfehlungen und neuen Schäden."),
        b("fs1","h2","Häufigste Schadensbilder im Baugutachten"),
        b("fs2","normal","Salzausblühungen an Kellerwänden deuten auf aufsteigende Feuchte oder seitliche Wassereinwirkung hin. Schimmel an Außenecken im Obergeschoss spricht für Wärmebrücken in Kombination mit erhöhter Raumluftfeuchte. Putzabplatzungen in Sockelbereichen weisen auf Spritzwasser oder fehlende horizontale Sperre. Tropfwasserspuren an Dachuntersichten sind typisch für Dachundichtigkeiten oder Tauwasserausfall in der Konstruktion. Wasserränder an Decken zeigen Leitungsschäden im darüber liegenden Geschoss."),
        b("fs3","h2","Ursachenkategorien – Bauphysik, Nutzung, Leitungsschaden, aufsteigende Feuchte"),
        b("fs4","normal","Drei Hauptursachen sind zu unterscheiden. Erstens bauphysikalische Mängel: fehlende oder mangelhafte Abdichtung nach DIN 18533, Wärmebrücken nach DIN 4108 Beiblatt 2, fehlende Luftdichtheit nach DIN 4108-7. Zweitens Leitungs- und Abwasserschäden: undichte Wasserleitungen, defekte Abwasserrohre, Leckagen. Drittens nutzungsbedingte Feuchte: Kondensat an Außenecken durch erhöhte Raumluftfeuchte ohne ausreichende Lüftung. Eine vierte Kategorie ist aufsteigende Feuchte aus dem Erdreich bei fehlender horizontaler Sperre."),
        b("fs5","h2","Messverfahren und Geräte"),
        b("fs6","normal","Die quantitative Erfassung der Feuchte ist Grundlage jedes belastbaren Feuchtigkeitsschäden-Gutachtens. Mehrere Verfahren stehen zur Verfügung, mit unterschiedlicher Eindringtiefe und Aussagekraft."),
        b("fs7","h3","Widerstandsmessung und kapazitive Verfahren"),
        b("fs8","normal","Widerstandsmessgeräte messen den elektrischen Widerstand zwischen zwei Elektroden – je feuchter das Material, desto niedriger der Widerstand. Vorteil: schnell, günstig. Nachteil: nur oberflächliche Messung (1 bis 2 cm Tiefe), salzempfindlich. Kapazitive Verfahren erreichen 3 bis 5 cm Eindringtiefe. Beide Verfahren liefern relative Werte, keine absoluten Feuchtigkeitsgehalte."),
        b("fs9","h3","Mikrowelle und Radar"),
        b("fs10","normal","Mikrowellen- und Radarverfahren erreichen bis zu 30 cm Eindringtiefe und sind materialunabhängig. Sie eignen sich für die Lokalisierung von Feuchtigkeit in tieferen Wandschichten. Quantitative Aussagen erfordern materialspezifische Kalibrierung."),
        b("fs11","h3","Darrtrocknung nach DIN EN ISO 12570"),
        b("fs12","normal","Bei Feuchtigkeitsschäden im Mauerwerk liefert die Darrtrocknung nach DIN EN ISO 12570 den justiziablen Referenzwert. Eine Materialprobe wird gewogen, im Trockenschrank bei 105 °C bis zur Massekonstanz getrocknet und erneut gewogen; aus der Massendifferenz ergibt sich der absolute Feuchtegehalt in Masseprozent. Die Methode ist zerstörend, aber die einzige, die einen gerichtsfesten Absolutwert liefert."),
        b("fs13","h3","Thermografie"),
        b("fs14","normal","Thermografie nach DIN EN 13187 visualisiert Temperaturunterschiede an der Bauteiloberfläche und damit indirekt Feuchte- und Wärmebrückenbereiche. Für eine quantitative Auswertung ist eine Temperaturdifferenz innen/außen von mindestens 15 K erforderlich. Beste Aufnahmezeit: frühe Morgenstunden im Winter bei stabilem Wetter."),
        b("fs15","h3","Raumklima- und CO2-Messung"),
        b("fs16","normal","Bei nutzungsbedingten Feuchtigkeitsschäden gehört die Raumklima-Messung zum Standard: Lufttemperatur, relative Feuchte und CO2-Konzentration über mindestens 14 Tage. Hohe CO2-Werte (über 1.500 ppm) deuten auf ungenügendes Lüften hin – ein wichtiges Indiz für nutzerbedingte Feuchte."),
        b("fs17","h2","Normative Grundlagen – DIN 4108-3, DIN 18533, DIN/TS 4108-8"),
        b("fs18","normal","DIN 4108-3:2024-03 regelt den klimabedingten Feuchteschutz mit dem Glaser-Verfahren zur Tauwasserberechnung. DIN 18195 enthält die Begriffe der Bauwerksabdichtung. DIN 18533 normiert die Abdichtung erdberührter Bauteile (W1 bis W4), DIN 18534 die Abdichtung von Innenräumen. DIN/TS 4108-8 bündelt das Vorgehen zur Schimmelvermeidung in Innenräumen."),
        b("fs19","h2","WTA-Merkblätter und UBA-Schimmelleitfaden"),
        b("fs20","normal","Neben den DIN-Normen sind die WTA-Merkblätter der Wissenschaftlich-Technischen Arbeitsgemeinschaft Stand der Praxis. Wichtige Merkblätter: 6-2 zur hygrothermischen Simulation, 6-5 zur Innendämmung, 4-5 zur Mauerwerksbeurteilung, 4-12 zur Kontrolle nach Schimmelsanierung. Der UBA-Schimmelleitfaden (Fassung 2017) ist die zentrale Referenz für Schimmelpilzbefall in Innenräumen."),
        b("fs21","h2","Schimmelgutachten – Abgrenzung Bauphysik versus Nutzerverhalten"),
        b("fs22","normal","Das Schimmelgutachten unterscheidet zwischen baulicher Ursache und nutzerbedingter Feuchtelast. Der entscheidende Maßstab: Erreicht die Oberflächentemperatur der Innenwand unter normalen Nutzungsbedingungen (20 °C Raumluft, 50 % relative Feuchte) den Taupunkt von 12,6 °C, liegt eine bauliche Ursache vor. Liegt die Oberflächentemperatur deutlich darüber, kommt nutzerbedingte Feuchte als Ursache in Betracht. Die Abgrenzung hat erhebliche zivilrechtliche Konsequenzen: bei baulicher Ursache haftet der Vermieter, bei nutzerbedingter Ursache der Mieter."),
        b("fs23","h2","Sanierungsbewertung und Beweissicherung"),
        b("fs24","normal","Die Sanierungsempfehlung folgt aus der Ursachenanalyse. Bauliche Ursachen erfordern bauliche Maßnahmen: nachträgliche Abdichtung, Wärmebrücken-Sanierung, Innendämmung nach WTA 6-5. Nutzungsbedingte Ursachen werden durch geänderte Lüftung adressiert. Die Beweissicherung erfolgt im streitigen Fall nach § 485 ZPO. Alle Messstellen sind lückenlos zu dokumentieren – mit Foto, Datum und Messwert."),
        b("fs25","h2","KI-gestützte Auswertung von Feuchtigkeitsdaten und Fotos"),
        b("fs26","normal","KI-Werkzeuge leisten dreierlei: Erstens Bilderkennung – Schadensbilder werden klassifiziert und mit typischen Ursachenmustern verknüpft. Zweitens automatische Übernahme von Messprotokollen – Messwerte, Geräte-IDs und Messzeitpunkte werden aus Geräte-Exports importiert. Drittens Plausibilitätsprüfung – die KI erkennt Widersprüche zwischen Schadensbild und Messwerten. Die Zuordnung zur Ursachenkategorie und die Sanierungsempfehlung bleiben sachverständige Tätigkeit nach § 407a Abs. 1 ZPO."),
        b("fs27","h2","Fazit"),
        b("fs28","normal","Systematisches Vorgehen: Schadensbildanalyse, Ursachenhypothesen, Messverfahren auswählen, Normen zuordnen (DIN 4108-3, DIN 18533, DIN/TS 4108-8), WTA-Merkblätter heranziehen, Abgrenzung Bauphysik/Nutzung über Oberflächentemperatur (Taupunkt 12,6 °C bei 20/50). Die Darrtrocknung nach DIN EN ISO 12570 liefert den gerichtsfesten Absolutwert."),
      ] });
    await client.createOrReplace({ _id: "post-software-vergleich", _type: "post",
      title: "Software für Bausachverständige im Vergleich: Funktionen, Preise und KI-Integration",
      slug: { _type: "slug", current: "bausachverstaendiger-software-vergleich" },
      category: "Vergleich",
      publishedAt: "2026-05-16",
      excerpt: "Software für Bausachverständige vergleichen: acht Funktionsbereiche, Preismodelle, DSGVO-Konformität und KI-Integration. Der systematische Entscheidungsrahmen für die Softwareauswahl.",
      body: [
        b("sv0","normal","Software für Bausachverständige unterstützt Fallverwaltung, JVEG-Abrechnung und Gutachten-Erstellung. Der Markt ist fragmentiert: klassische Desktop-Lösungen aus den 2000ern stehen neben modernen Cloud-Plattformen mit KI-Funktionen."),
        b("sv1","h2","Worauf Bausachverständige bei Software achten sollten"),
        b("sv2","normal","Drei Fragen klären vor jeder Auswahl. Erstens: Welche Auftragslage liegt vor? Solo-Sachverständige mit unter 30 gerichtlichen Aufträgen pro Jahr brauchen andere Werkzeuge als ein Büro mit fünf Mitarbeitern und 200 Aufträgen jährlich. Zweitens: Welche Sachgebiete werden bearbeitet? Drittens: Welcher Digitalisierungsgrad ist bereits erreicht?"),
        b("sv3","h2","Funktionsbereiche im Vergleich"),
        b("sv4","h3","Fallverwaltung mit digitaler Akte"),
        b("sv5","normal","Die Fallverwaltung ist das Rückgrat. Eine digitale Akte führt alle Dokumente eines Verfahrens zusammen: Beweisbeschluss, Schriftsätze, Anlagen, Lichtbilder, Korrespondenz, Honorarnoten. Moderne Lösungen importieren Anlagen aus E-Mail oder eBO direkt in die Akte. Volltextsuche über alle Akten spart bei wiederkehrenden Fragen erhebliche Zeit."),
        b("sv6","h3","Beweisbeschluss-Analyse mit Frage-Extraktion"),
        b("sv7","normal","Moderne KI-gestützte Tools extrahieren aus dem Beweisbeschluss die nummerierten Beweisfragen und schlagen eine Gutachten-Gliederung vor. Mehrfachfragen in einem Satz werden erkannt und zur Aufgliederung markiert. Anknüpfungstatsachen werden gegen die Akte abgeglichen."),
        b("sv8","h3","Foto- und Beweisstück-Verwaltung mit Geo-Tagging"),
        b("sv9","normal","Foto-Verwaltung mit GPS-Koordinaten, Zeitstempel und Zuordnung zur Beweisfrage ist Standard. Wichtig ist die Verknüpfung: welche Fotos sind für das Gutachten erforderlich (für die JVEG-Abrechnung nach § 12 JVEG relevant)?"),
        b("sv10","h3","Ortstermin-Tools mit Offline-Fähigkeit"),
        b("sv11","normal","Mobile Apps für den Ortstermin müssen offline funktionieren – Baustellen, Keller und Dachstühle haben keinen WLAN-Empfang. Die App nimmt Fotos auf, schreibt Notizen, erfasst Messwerte, dokumentiert Zeit. Wer hier auf reine Online-Tools setzt, riskiert Datenverlust beim Ortstermin."),
        b("sv12","h3","Gutachten-Erstellung mit Vorlagen"),
        b("sv13","normal","Strukturierte Vorlagen für Standard-Abschnitte (Auftrag, Sachverhalt, Beweisfragen, Befund, Beurteilung, Zusammenfassung) sichern Konsistenz und beschleunigen die Reinschrift. Wichtig: Textbausteine werden zentral gepflegt, Befunde aus der Akte automatisch eingefügt."),
        b("sv14","h3","JVEG-Abrechnung mit Zeiterfassung nach § 9 JVEG"),
        b("sv15","normal","Die richtige Software automatisiert die JVEG-Abrechnung. Stundensatz wird aus dem Beweisbeschluss abgeleitet, Schreibgebühr aus den tatsächlichen Anschlägen, Foto-Pauschale aus den als erforderlich markierten Fotos. Plausibilitätsprüfung gegen JVEG-Vorgaben mindert Kürzungsrisiken."),
        b("sv16","h3","KI-Funktionen – Diktat, Klassifikation, Recherche"),
        b("sv17","normal","Diktat-zu-Text mit Fachsprache-Adaption erreicht über 95 Prozent Wortgenauigkeit. Schadensbild-Vorklassifikation aus Fotos liefert Hypothesen zur Ursache. Semantische Normenrecherche findet zu Schadensbildern die passenden DIN-Normen und WTA-Merkblätter."),
        b("sv18","h3","Schnittstellen zum eBO, DATEV, ERP"),
        b("sv19","normal","Die Schnittstelle zum eBO nach § 130a Abs. 4 Nr. 4 ZPO ist seit 2024 praxisrelevant – sie ermöglicht den direkten Versand des Gutachtens an das Gericht. DATEV-Schnittstellen automatisieren die Buchhaltung."),
        b("sv20","h2","Anbieterüberblick – etablierte und neue Lösungen"),
        b("sv21","normal","Der Markt teilt sich in drei Segmente. Erstens etablierte Klassiker: BauSV/SV-Office, Sachgut, ImmoSV – Desktop-Lösungen mit langjähriger Marktpräsenz und umfassendem Funktionsumfang, aber eher konservativer Oberfläche und begrenzter KI-Integration. Zweitens neuere Cloud-Lösungen mit KI-Fokus wie Gutachten-Assistent – modulare Architektur, EU-Hosting, integrierte KI-Funktionen, monatliches Abo. Drittens generalistische Tools mit Bau-Anwendung wie autarc.energy für Energieberatung. Eine pauschale Empfehlung verbietet sich – die richtige Wahl hängt von der eigenen Auftragsstruktur ab."),
        b("sv22","h2","Preisstrukturen und Lizenzmodelle"),
        b("sv23","normal","Drei Modelle dominieren. Erstens Einmal-Lizenz mit jährlicher Wartung: typischerweise 1.500 bis 4.000 Euro einmalig plus 200 bis 500 Euro Wartung pro Jahr. Planbare Gesamtkosten, aber hohe Anfangsinvestition. Zweitens Cloud-Abo: 40 bis 120 Euro pro Nutzer und Monat. Kontinuierliche Updates, niedrige Einstiegshürde, aber langfristig teurer. Drittens Pay-per-Gutachten: selten, sinnvoll für sehr geringe Auftragslage."),
        b("sv24","h2","Datenschutz und DSGVO-Konformität"),
        b("sv25","normal","Sachverständige verarbeiten personenbezogene Daten. Pflicht: AV-Vertrag nach Artikel 28 DSGVO, Verarbeitungsverzeichnis nach Artikel 30, bei besonderen Kategorien auch DSFA nach Artikel 35. Hosting in DE oder EU mit Schrems-II-Compliance ist Mindestanforderung bei Gerichtsaufträgen."),
        b("sv26","h2","Auswahlkriterien für die Entscheidung"),
        b("sv27","normal","Fünf harte Kriterien: Datenexport (kann ich Akten als PDF/A oder JSON exportieren?), Skalierbarkeit, deutschsprachiger Support, Schulung und Onboarding, Referenzen von anderen Bausachverständigen. Drei Profile helfen: Profil A – Solo unter 30 Aufträgen/Jahr: schlanke Cloud-Lösung, monatlich kündbar. Profil B – Büro 30 bis 150 Aufträge: Team-Funktionen, ERP-Schnittstellen. Profil C – KI-Fokus: Cloud-Plattform mit KI-Modulen, EU-Hosting, offene API."),
        b("sv28","h2","Fazit"),
        b("sv29","normal","Die Software-Entscheidung ist eine 5-Jahres-Entscheidung – der Wechsel kostet Zeit und Daten. KI-Funktionen sind 2026 kein optionales Extra mehr, sondern Standard. Die richtige Software automatisiert die JVEG-Abrechnung nach § 9 und § 12 JVEG, beschleunigt die Beweisbeschluss-Analyse und unterstützt den elektronischen Rechtsverkehr über das eBO."),
      ] });
    await client.createOrReplace({ _id: "post-eu-ai-act-gutachtenwesen", _type: "post",
      title: "EU AI Act im Gutachtenwesen: Pflichten für Sachverständige und KI-Anbieter ab August 2026",
      slug: { _type: "slug", current: "eu-ai-act-gutachtenwesen" },
      category: "KI & Recht",
      publishedAt: "2026-05-16",
      excerpt: "Der EU AI Act betrifft Sachverständige mittelbar über die KI-Software, mit der sie arbeiten. Anhang III Nr. 8 erfasst KI in der Justiz – aber nicht jede Gutachten-KI. Hochrisiko-Pflichten gelten ab 02.08.2026.",
      body: [
        b("ai0","normal","Der EU AI Act (Verordnung (EU) 2024/1689) ist am 01.08.2024 in Kraft getreten. Ab dem 02.08.2026 gelten die Hochrisiko-Pflichten in vollem Umfang. Dieser Beitrag ordnet die Verordnung rechtlich präzise ein und korrigiert ein verbreitetes Missverständnis zu Anhang III Nr. 8."),
        b("ai1","h2","Was regelt der EU AI Act und wann gelten welche Pflichten"),
        b("ai2","normal","Die Anwendbarkeit folgt einem gestaffelten Zeitplan: Verbote nach Artikel 5 gelten seit 02.02.2025, Pflichten für General-Purpose-AI-Modelle seit 02.08.2025, Hochrisiko-Pflichten für Anhang-III-Systeme treten am 02.08.2026 in Kraft. Die Verordnung gilt unmittelbar in allen EU-Mitgliedstaaten. Adressaten sind insbesondere Anbieter und Betreiber von KI-Systemen."),
        b("ai3","h2","Vier Risikoklassen der KI-Verordnung im Überblick"),
        b("ai4","normal","Erstens verbotene Praktiken nach Artikel 5 (Social Scoring, manipulative Techniken, biometrische Echtzeit-Fernidentifizierung). Zweitens Hochrisiko-KI nach Artikel 6 in Verbindung mit Anhang III: KI in kritischen Bereichen wie Bildung, Beschäftigung, kritische Infrastruktur, Strafverfolgung, Migration und Rechtspflege. Drittens begrenztes Transparenzrisiko nach Artikel 50: Chatbots und KI-generierter Content müssen als solche erkennbar sein. Viertens minimales Risiko: alle übrigen KI-Systeme."),
        b("ai5","h2","Anhang III Nr. 8 – KI in der Rechtspflege als Hochrisiko-Anwendung"),
        b("ai6","h3","Wortlaut und Erwägungsgrund 61"),
        b("ai7","normal","Anhang III Nr. 8 lit. a erfasst KI-Systeme, die bestimmungsgemäß von einer Justizbehörde oder in deren Namen verwendet werden, um eine Justizbehörde bei der Ermittlung und Auslegung von Sachverhalten und Rechtsvorschriften und bei der Anwendung des Rechts auf konkrete Sachverhalte zu unterstützen. Erwägungsgrund 61 stellt klar: Erfasst sind nur KI-Systeme, die als Werkzeug der Justizbehörde selbst dienen und in die richterliche Entscheidungsfindung eingreifen. Hilfssysteme, die lediglich vorbereitende Arbeiten erleichtern, sind ausgenommen."),
        b("ai8","h3","Warum Gutachten-KI in der Regel keine Justizbehörden-Anwendung ist"),
        b("ai9","normal","Eine KI-Software, die einen Sachverständigen bei der Erstellung eines Gerichtsgutachtens unterstützt, fällt nicht automatisch unter Anhang III Nr. 8 lit. a. Der Sachverständige ist nach ständiger Rechtsprechung keine Justizbehörde, sondern weisungsgebundener Berater des Gerichts (OLG Hamm 32 W 7/16). Die KI-Software des Sachverständigen ist ein Hilfsmittel des Beraters, nicht der Justizbehörde. Sie fällt nur dann unter Anhang III Nr. 8, wenn sie bestimmungsgemäß von der Justizbehörde selbst eingesetzt wird oder die richterliche Entscheidung ersetzt."),
        b("ai10","h2","Wann eine KI-gestützte Gutachten-Software Hochrisiko wird"),
        b("ai11","normal","Auch ohne die Regelvermutung für Hochrisiko können einzelne Anwendungsfälle als Hochrisiko einzuordnen sein: Wenn die KI in Anhang I als Sicherheitsbauteil gelistet ist (Bauprodukte-Verordnung), greift Artikel 6 Abs. 1. Wenn die KI biometrische Daten verarbeitet, können andere Nummern aus Anhang III einschlägig werden. Die Selbsteinordnung des Anbieters als Hochrisiko ist nach Artikel 6 Abs. 4 immer möglich und verlangt schriftliche Dokumentation."),
        b("ai12","h2","Ausnahme nach Art. 6 Abs. 3 KI-VO für verfahrensbezogene Aufgaben"),
        b("ai13","normal","Art. 6 Abs. 3 EU AI Act schließt Hochrisiko aus, wenn das KI-System eine eng umrissene verfahrensbezogene Aufgabe erfüllt, das Ergebnis menschlicher Tätigkeit verbessert oder lediglich eine vorbereitende Bewertung liefert. Anwendungsbeispiele: Strukturierung einer Akte, Extraktion von Beweisfragen, Erkennung von Schadensbildmustern als Vorschlag für den Sachverständigen. Profiling natürlicher Personen schließt die Ausnahme nach Art. 6 Abs. 3 UAbs. 2 aus."),
        b("ai14","h2","Anbieter- und Betreiberpflichten nach Art. 16 und Art. 26 KI-VO"),
        b("ai15","normal","Anbieter tragen die Hauptlast: Artikel 16 listet vierzehn Anbieterpflichten auf – Konformitätsbewertung, technische Dokumentation, Risikomanagement, Daten-Governance, Transparenz, menschliche Aufsicht, Cybersicherheit, CE-Kennzeichnung. Sachverständige als Betreiber nach Artikel 26: Befolgen der Anbieter-Anweisungen, Sicherstellen menschlicher Aufsicht, Kontrolle der Eingabedaten, Aufbewahrung automatisch erzeugter Protokolle. Sachverständige dokumentieren außerdem, in welchem Umfang KI bei der Gutachtenerstellung eingesetzt wurde – dies folgt aus § 407a ZPO."),
        b("ai16","h2","Sanktionen bei Verstößen gegen den EU AI Act"),
        b("ai17","normal","Die Sanktionsstruktur ist drei-stufig (Artikel 99). Stufe eins: Verstöße gegen Verbote nach Artikel 5 bis zu 35 Millionen Euro oder 7 Prozent des weltweiten Jahresumsatzes. Stufe zwei: Verstöße gegen Hochrisiko-Pflichten bis zu 15 Millionen Euro oder 3 Prozent. Stufe drei: Bereitstellung falscher Angaben bis zu 7,5 Millionen Euro oder 1 Prozent. KMU und Start-ups sind nach Art. 99 Abs. 6 privilegiert."),
        b("ai18","h2","Wie Sachverständige sich auf den 02.08.2026 vorbereiten"),
        b("ai19","normal","Vier Schritte: Erstens Bestandsaufnahme der eingesetzten KI-Tools (Diktat, Aktenanalyse, Bildauswertung, Normenrecherche). Zweitens Risikoeinordnung pro Tool – schriftlich dokumentiert. Drittens Vertragsmanagement mit den KI-Anbietern (AV-Vertrag nach Artikel 28 DSGVO). Viertens Schulung des eigenen Teams. Seit 02.02.2025 gilt nach Artikel 4 EU AI Act die KI-Kompetenz-Pflicht: Anbieter und Betreiber sorgen für hinreichende KI-Kompetenz ihres Personals."),
        b("ai20","h2","Fazit"),
        b("ai21","normal","Der EU AI Act betrifft das Gutachtenwesen mittelbar über die KI-Software, mit der Sachverständige arbeiten. Anhang III Nr. 8 erfasst KI in der Justiz – nicht jede Gutachten-KI. Wer KI-Systeme im Gutachtenwesen anbietet, prüft zuerst Art. 6 Abs. 3 auf eine mögliche Ausnahme und dokumentiert das Ergebnis nach Art. 6 Abs. 4. Sachverständige als Betreiber tragen die Pflichten aus Art. 26. Bis 02.08.2026 ist Zeit für eine systematische Bestandsaufnahme."),
      ] });
    await client.createOrReplace({ _id: "post-beweisbeschluss-ki-auswertung", _type: "post",
      title: "Beweisbeschluss strukturiert auswerten: Wie KI Sachverständigen bei der Auftragsanalyse hilft",
      slug: { _type: "slug", current: "beweisbeschluss-ki-auswertung" },
      category: "Technik",
      publishedAt: "2026-05-16",
      excerpt: "Der Beweisbeschluss bestimmt den Auftragsrahmen nach § 404a ZPO. Wer ihn nicht versteht oder Teilfragen übersieht, riskiert Ergänzungsgutachten. Systematisches Vorgehen und KI-gestützte Analyse für Bausachverständige.",
      body: [
        b("bb0","normal","Der Beweisbeschluss bestimmt den Auftragsrahmen des Sachverständigen nach § 404a ZPO. Wer ihn nicht versteht oder Teilfragen übersieht, riskiert Nachfragen des Gerichts und Ergänzungsgutachten."),
        b("bb1","h2","Der Beweisbeschluss als Auftragsgrundlage des Sachverständigen"),
        b("bb2","normal","Der Beweisbeschluss definiert das Beweisthema, formuliert die einzelnen Beweisfragen, benennt die zu beachtenden Anknüpfungstatsachen und gibt der oder dem Sachverständigen den Rahmen für die Ermittlungsbefugnisse vor. Der Beweisbeschluss bindet den Sachverständigen rechtlich – über seinen Rahmen hinaus tätig zu werden bedeutet eigenmächtige Auftragserweiterung und wird vergütungsrechtlich nicht erstattet."),
        b("bb3","h2","Rechtliche Grundlagen – §§ 404, 404a, 407a ZPO"),
        b("bb4","normal","§ 404 ZPO regelt die Auswahl: Das Prozessgericht bestimmt den Sachverständigen, wobei öffentlich bestellte und vereidigte Sachverständige nach Absatz 3 Vorrang haben. § 404a ZPO regelt die Leitung der Sachverständigentätigkeit durch das Gericht. Absatz 3 weist dem Gericht die Festlegung der zugrunde zu legenden Tatsachen bei streitigem Sachverhalt zu. § 407a ZPO regelt die Pflichten der Sachverständigen: unverzügliche Prüfung der eigenen Sachkunde, Hinweispflicht bei Befangenheitsgrund oder Auftragserweiterung."),
        b("bb5","h2","Anatomie eines Beweisbeschlusses"),
        b("bb6","h3","Beweisthema und Beweisfragen"),
        b("bb7","normal","Das Beweisthema benennt den Gegenstand der Begutachtung. Darunter folgen nummerierte Beweisfragen, die das Thema in einzelne Tatsachenkomplexe zerlegen. Jede Beweisfrage ist eigenständig zu beantworten. Wer im Gutachten die Reihenfolge der Fragen verändert oder Fragen zusammenfasst, schafft Unklarheit."),
        b("bb8","h3","Anknüpfungstatsachen"),
        b("bb9","normal","Anknüpfungstatsachen sind die Tatsachen, von denen der Sachverständige bei seiner Begutachtung auszugehen hat. Nach § 404a Abs. 3 ZPO ist das Gericht für die Festlegung der Anknüpfungstatsachen zuständig, wenn der Sachverhalt streitig ist. Der Sachverständige beurteilt nicht, was wahr ist, sondern was unter Annahme der vom Gericht festgelegten Tatsachen technisch zu sagen ist."),
        b("bb10","h3","Weisungen nach § 404a ZPO"),
        b("bb11","normal","Das Gericht kann konkrete Weisungen erteilen: bestimmte Materialien zu untersuchen, bestimmte Verfahren anzuwenden, Parteivertreter zum Ortstermin zu laden. Diese Weisungen sind bindend."),
        b("bb12","h2","Häufige Probleme – unklare Beweisfragen, fehlende Anknüpfungstatsachen"),
        b("bb13","normal","Beweisfragen, die mehrere Tatsachenkomplexe in einem Satz vermengen, müssen aufgegliedert werden. Beweisfragen mit unklarem Bezugspunkt bleiben rechtlich, nicht sachverständig. Fehlende Anknüpfungstatsachen bei streitigem Sachverhalt erfordern Rücksprache – der Sachverständige kann nicht selbst entscheiden, welche Version er zugrunde legt. Bei Unklarheiten verlangt § 404a Abs. 2 ZPO die Rücksprache mit dem Gericht."),
        b("bb14","h2","Pflichten nach § 407a ZPO bei der Auftragsannahme"),
        b("bb15","normal","Mit Erhalt des Beweisbeschlusses treten die Pflichten aus § 407a ZPO ein. Erstens: unverzügliche Prüfung, ob der Auftrag in das eigene Sachgebiet fällt. Zweitens: Hinweispflicht auf Befangenheitsgründe. Drittens: Hinweispflicht bei Auftragserweiterung. Viertens: ordnungsgemäße Aktenherausgabe bei Erledigung. Ihre Verletzung kann zur Honorarkürzung und zur Haftung führen."),
        b("bb16","h2","KI-gestützte Auswertung des Beweisbeschlusses"),
        b("bb17","h3","Extraktion der Beweisfragen"),
        b("bb18","normal","Das KI-System liest den Beweisbeschluss und extrahiert die nummerierten Beweisfragen automatisch. Dabei erkennt es Mehrfachfragen, die in einem Satz zusammengefasst sind, und schlägt eine Aufgliederung in Teilfragen vor. Die fachliche Entscheidung, ob die Aufgliederung übernommen wird, bleibt bei der Sachverständigen."),
        b("bb19","h3","Identifikation der Anknüpfungstatsachen"),
        b("bb20","normal","Die KI markiert im Beweisbeschluss die vom Gericht festgelegten Anknüpfungstatsachen und gleicht sie gegen die Aktenlage ab. Lücken werden markiert – etwa wenn das Gericht eine streitige Tatsache nicht festgelegt hat."),
        b("bb21","h3","Plausibilitätsprüfung gegen die Akte"),
        b("bb22","normal","Die KI prüft, ob die im Beweisbeschluss genannten Anknüpfungstatsachen und Beweismittel in der beigezogenen Akte enthalten sind. Fehlende Anlagen oder Protokolle werden markiert. Bei umfangreichen Akten liefert die Volltext-Recherche schnelle Treffer für die Detailauswertung."),
        b("bb23","h2","Wann der Sachverständige Rücksprache mit dem Gericht halten muss"),
        b("bb24","normal","Konkrete Anlässe für Rücksprache nach § 404a Abs. 2 ZPO: unklare oder mehrdeutige Beweisfragen, fehlende Anknüpfungstatsachen bei streitigem Sachverhalt, Auftragserweiterung, fehlende Beweismittel oder Akten. Die Rücksprache erfolgt schriftlich mit konkret formulierten Klärungsfragen. Eigenmächtige Umformulierung der Beweisfragen ist unzulässig."),
        b("bb25","h2","Fazit"),
        b("bb26","normal","Die strukturierte Auswertung des Beweisbeschlusses ist die Grundlage jedes Gutachtens. Wer Beweisthema, Beweisfragen und Anknüpfungstatsachen sauber identifiziert, vermeidet Nachfragen und Ergänzungsgutachten. KI-Software unterstützt die Extraktion, identifiziert Lücken und prüft die Plausibilität gegen die Akte – die fachliche Würdigung bleibt bei der Sachverständigen."),
      ] });
    await client.createOrReplace({ _id: "post-digitale-akte-sachverstaendige", _type: "post",
      title: "Die digitale Akte für Sachverständige: eBO, § 130a ZPO und der Weg zum elektronischen Gutachten",
      slug: { _type: "slug", current: "digitale-akte-sachverstaendige" },
      category: "Praxis",
      publishedAt: "2026-05-16",
      excerpt: "Die digitale Akte für Sachverständige ist seit 01.01.2024 in § 173 Abs. 2 ZPO grundgelegt. Gutachten werden über das eBO nach § 130a Abs. 4 Nr. 4 ZPO elektronisch eingereicht. Rechtliche Grundlagen, technische Anforderungen und praktischer Workflow.",
      body: [
        b("da0","normal","Die digitale Akte für Sachverständige ist seit 01.01.2024 in § 173 Abs. 2 ZPO grundgelegt. Sachverständige reichen Gutachten elektronisch über das eBO nach § 130a Abs. 4 Nr. 4 ZPO ein. Die digitale Akte und das elektronische Gutachten setzen PDF/A-Format und einen XJustiz-Strukturdatensatz voraus."),
        b("da1","h2","Warum Sachverständige am elektronischen Rechtsverkehr teilnehmen"),
        b("da2","normal","Der elektronische Rechtsverkehr (ERV) verbindet Sachverständige direkt mit den Gerichten. Vorteile: keine Versandzeit, keine Versandkosten, lückenlose Übermittlungsnachweise, sofortiger Zugang beim Gericht. Bei dringenden Anhörungsterminen oder Ergänzungsfristen sind das entscheidende Stunden. Daneben spart der ERV Druck-, Kuvertier- und Frankierkosten – bei Vielnutzern jährlich vierstellige Beträge."),
        b("da3","h2","Rechtsgrundlagen – §§ 130a, 130d, 173 ZPO und ERVV"),
        b("da4","normal","§ 130a ZPO ist die zentrale Vorschrift zur elektronischen Einreichung. § 130d ZPO regelt seit 01.01.2022 die Pflicht zur aktiven elektronischen Übermittlung für professionelle Einreicher. § 173 ZPO regelt die Zustellung an einen sicheren Übermittlungsweg. Die ergänzende Elektronischer-Rechtsverkehr-Verordnung (ERVV) regelt die technischen Standards. Parallel gelten ähnliche Regelungen in StPO, FamFG, ArbGG, VwGO, SGG und FGO."),
        b("da5","h2","Drei Wege zur sicheren elektronischen Einreichung"),
        b("da6","h3","eBO – das zentrale Postfach für Sachverständige"),
        b("da7","normal","Das eBO wurde durch das ERV-Ausbaugesetz vom 05.10.2021 geschaffen und ist seit 01.01.2022 die zentrale Schnittstelle für Sachverständige. Vorteil: Die qualifizierte elektronische Signatur ist beim eBO-Versand verfahrensrechtlich nicht erforderlich, weil die Authentifizierung am Postfach diese Funktion übernimmt – so ausdrücklich der BGH im Beschluss vom 19.01.2023 (V ZB 28/22) zu § 130a Abs. 3 S. 1 Alt. 2 ZPO."),
        b("da8","h3","Absenderauthentifizierte De-Mail"),
        b("da9","normal","De-Mail nach § 130a Abs. 4 Nr. 1 ZPO ist eine Alternative, aber nur mit der Variante \"absenderauthentifiziert\" – die einfache De-Mail genügt nicht. In der Praxis ist De-Mail bei Sachverständigen wenig verbreitet."),
        b("da10","h3","EGVP mit qualifizierter elektronischer Signatur"),
        b("da11","normal","Das Elektronische Gerichts- und Verwaltungspostfach (EGVP) ohne sicheren Übermittlungsweg verlangt die qualifizierte elektronische Signatur (qeS). Wer mit EGVP und Signaturkarte einreicht, signiert jedes Dokument einzeln – aufwendig, aber rechtlich zulässig."),
        b("da12","h2","Technische Anforderungen – PDF/A, XJustiz-Strukturdatensatz"),
        b("da13","normal","Dokumente müssen im PDF/A-1 oder PDF/A-2-Format eingereicht werden – diese Formate sind langzeitarchivfähig. Schreib- oder Kopierschutz ist unzulässig. Jede Einreichung wird durch einen XJustiz-Strukturdatensatz begleitet – eine XML-Datei mit Metadaten zum Verfahren (Aktenzeichen, Beteiligte, Dokumenttyp). Der Strukturdatensatz wird von der eBO-Software automatisch erzeugt."),
        b("da14","h2","ERVB 2025 – was sich aktuell geändert hat"),
        b("da15","normal","Die Elektronischer-Rechtsverkehr-Bekanntmachung (ERVB) 2025 ist am 29.07.2025 im Bundesanzeiger erschienen. Wesentliche Neuerung: USB-Speichermedien mit exFAT- oder NTFS-Dateisystem sind als zusätzliche Datenträger zugelassen – relevant, wenn umfangreiche Lichtbilder oder Videodaten den E-Mail-Versand sprengen."),
        b("da16","h2","Passive Nutzungspflicht für Sachverständige seit 01.01.2024"),
        b("da17","normal","§ 173 Abs. 2 S. 1 Nr. 1 ZPO verlangt seit 01.01.2024, dass in professioneller Eigenschaft am Prozess Beteiligte einen sicheren Übermittlungsweg eröffnen. Wer regelmäßig gerichtlich beauftragt ist, fällt unter die Vorschrift und sollte ein eBO einrichten. Die Folge bei Nichteinrichtung: Zustellungen erfolgen weiter per Papierpost, der Sachverständige verliert die Geschwindigkeitsvorteile des ERV."),
        b("da18","h2","Workflow für das elektronische Gutachten"),
        b("da19","normal","Fünf Schritte: Erstens Gutachten als PDF/A speichern (Tagged-PDF mit Lesezeichen für Beweisfragen erhöht die Lesbarkeit). Zweitens Anlagen als separate PDF/A-Dateien anfügen. Drittens XJustiz-Strukturdatensatz erzeugen. Viertens Versand über das eBO an das Gericht (Aktenzeichen und Empfänger-Postfach vorab prüfen). Fünftens Empfangsbekenntnis prüfen – die Übermittlungsnachweise sind nach § 130a Abs. 5 ZPO maßgeblich für den Zugang."),
        b("da20","h2","Häufige Fehler und Risiken"),
        b("da21","normal","Drei Fehler treten regelmäßig auf. Erstens Einreichung als Word-Datei statt PDF/A – das Gericht weist zurück, die Frist ist nur unter engen Voraussetzungen von § 130a Abs. 6 ZPO gewahrt. Zweitens Kopierschutz oder Schreibsperre im PDF – die Datei wird zurückgewiesen. Drittens Einreichung per EGVP ohne qeS und ohne eBO – ebenfalls zurückgewiesen."),
        b("da22","h2","Fazit"),
        b("da23","normal","Die digitale Akte für Sachverständige ist 2026 praktischer Standard. Wer regelmäßig gerichtliche Aufträge bearbeitet, richtet ein eBO ein, hinterlegt es in der eigenen Software und reicht Gutachten als PDF/A mit XJustiz-Strukturdatensatz ein. Der BGH hat im Beschluss V ZB 28/22 klargestellt, dass beim eBO keine qeS erforderlich ist – das senkt die Hürde erheblich."),
      ] });

    return NextResponse.json({ success: true, message: "homePage + datenschutz + kontaktPage + ablaufPage + funktionenPage + 9 Blog-Posts erfolgreich eingespielt." });

  } catch (error) {
    return NextResponse.json({ success: false, error: String(error) }, { status: 500 });
  }
}
